# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5be6e3aff20288b6f35e3df5f1062b0ac7b7b2696736e7d6a991647ea630f46e4283cd3e680b02f1960981a9359e1ac3f431e510f33cc18788ea964e4e344d

test:
  secret_key_base: 8e5705a83b1ba3198093e74b6d38054fcebb24e7314d5450a66879a46fa6b26d8b69a71736afba1f23a7b2ee1cfec52a3cfba213e0c544cb61ad66ddbc20acfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
